#+title: Avaliação comparativa de três pacotes Python para redes complexas

* Metodologia
** [X] Criação do ambiente virtual e instalação dos pacotes
    Essa seção compreende os itens 1 ao 4 do projeto.
** [X] Aprendizado do uso dos pacotes
    Essa seção compreende o item 5 listado no projeto.
** [ ] Catalação das funcionalidades
    Essa seção compreende o item 6 no projeto.
** [ ] Ánalise comparativa de desempenho    
    Item 7 do projeto.
** [ ] Simulações [2/3]
    Item 8 do projeto.
    - [X] Percolação em grafos aleatórios no modelo de Erdos-Renyi.
    - [X] Efeito de mundo pequeno nos grafos de Watts-Strogatz.
    - [ ] Resiliência a ataques aleatórios e direcionados em redes sem escala no modelo Albert-Barabasi.
* Analise de resultados      
  Itens retirados do projeto:
  - [ ] Parte 1 à 4: Comparação da dificuldade de instalação dos pacotes.
  - [ ] Parte 5: Comparação da dificuldade de aprendizado de uso dos pacotes, tanto em termos da disponibilidade de
           boa documentação on-line quanto da própria organização dos pacotes.
  - [ ] Parte 6: Comparação da abrangência dos pacotes, em termos das funcionalidades prontas
    fornecidas.
  - [ ] Comparação do desempenho dos pacotes, verificando se existe uma vantagem geral para algum dos pa-
       cotes ou se o desempenho relativo varia de uma funcionalidade para outra. Aqui deve ser verificado
       estatisticamente se existe diferença significativa entre as médias de tempo de execução. Por outro lado,
       ao tirar conclusões nesse ponto deve-se levar em consideração que os códigos serão executados em apenas
       um computador, e portanto os resultados podem ser diferentes em outros computadores, especialmente se
       as diferenças de tempo forem pequenas.
