#+title: Projeto PUB
#+setupfile: ~/Dropbox/Templates/physics.org
* DONE Parte 1: Instalação de pacotes e ambientes virtuais 
   Necessário instalar o pacote =graph-tool= novamente.
*** Máquina virtual
   - Distribuição: =Ubuntu=
*** pip
   Aqui está o [[https://docs.python.org/3/library/venv.html][link]] para a documentação utilizada como referência na criação dos ambientes virtuais
   com =venv= .
   Para olhar a quantidade de disco utilizado:
   Os pacotes instalados ficam localizados no diretório
   =env_name/lib/python3.10/site-packages/= - onde =env_name= é o nome do ambiente virtual -
   para saber a quantidade de disco utilizado usamos o comando abaixo:
   #+begin_src shell
     du env_name/lib/python3.10/site-packages
   #+end_src
**** Networkx 
    - Sem dificuldades na instalação.
    - Quantidade de disco utilizado: *32M*
**** igraph
   - Sem dificuldades na instalação.
   - Quantidade de disco utilizado: *29M*
**** graph-tools
   - Sem dificuldades na instalação.
   - Quantidade de disco utilizado: *87M*
*** conda
   Este é o [[https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands][link]] da documentação do =conda= utilizada nessa etapa.
   Para verificar a quantidade de disco utilizando =conda= foi usado o seguinte
   comando
   #+begin_src shell
     du -sh $(conda info --b)"/envs/$conda_env"
   #+end_src
   onde =$conda_env= é o nome do ambiente =conda= criado. 
**** Networkx
   - Sem dificuldades na instalação.
   - Quantidade de disco utilizada: *208M*
**** igraph
   - Para realizar a instalação desse pacote no =conda= foi necessário
     olhar a [[https://anaconda.org/conda-forge/python-igraph][documentação]], pois não se instala com simplesmente o comando
     =conda install pacote=.
   - Quantidade de disco utilizada: *279M*
**** graph-tools
   - A instalação do =graph-tools= apresentou as mesmas dificuldades da do =igraph=.
   - Quantidade de disco utilizada: *1.4GB*
* TODO Parte 2: Aprendizado e uso dos pacotes
  - Nessa etapa, documentei o "reteiro" que segui para aprender usar os pacotes, talvez pode ser
   relevante também incluir isso no projeto?
  - Além disso quero saber se a forma como devo escrever sobre os pacotes individualmente deva
    ser parecida com o artigo da bibliográfia "Array programming with numpy"?
   - Eles fazem uma descrição bem detalhada do pacote que acho que posso me inspirar, eles citam
    exemplos de tecnologias ou grupos de pesquisa que utilizam o pacote e como, além de também
    se aprofundar bastante no funcionamento do numpy.
  - [X]  NetworkX
  - [X]  igraph
  - [ ]  graph-tools
* TODO Parte 3: Catalogação de funcionalidade dos pacotes
     - Com "funcionalidade" estamos nos referindo a toda a gama de métodos e funções
       que os três pacotes oferecem? 
     - Funcionalidades pode ser mais relacionado a algoritmos importantes no estudo de redes, como
       por exemplo os que computam medidas de centralidade, conectividade ou de agrupamentos.  
     - Como devo estruturar o relatório do projeto?        
     - [ ] Comparar abrangência de funcionalidades [0/3]
       - [ ] NetworkX
       - [ ] igraph
       - [ ] graph-tools    
     - [ ] Notar possíveis limitações dos pacotes em questão [0/3]
       - [ ] NetworkX
       - [ ] igraph
       - [ ] graph-tools    
* TODO Parte 4: Analise comparativa de desempenho dos pacotes
  - Devo explicar o que as funcionalidades escolhidas para as analises são?
    Descrição dos algoritmos, etc.
* TODO Parte 5: Simulações de resultados de redes complexas [2/3]
   - Quero sugestão de mais simulações para reproduzir no projeto.
   - [X] Reproduzir o resultado de percolação em redes de Erdős e Rényi.
   - [X] Reproduzir o resultado sobre o efeito de mundo pequeno de Watts e Strogatz.
   - [ ] Reproduzir o resultado de resiliência a ataques aleatórios e direcionados de redes com distribuição
     de grau livre de escala de Albert, Jeong e Barabási.
* Referencias
** Livros 
  - First course in network science - Ernesto Estrada.
  - Complex Networks - an Introduction - Newman.
** Papers 
  - [[~/Dropbox/Papers/Array programming with NumPy.pdf][~/Papers/Array programming with NumPy.pdf]]
    Devo buscar escrever de forma detalhada como neste artigo?
    - Com explicações aprofundadas sobre comportamento da biblioteca, com exemplos
      de projetos que usam elas e descrição de algumas das funcionalidades.
  - [[~/Dropbox/Papers/SciPy.pdf][~/Papers/SciPy.pdf]]
  - [[~/Dropbox/Papers/WattsStrogatz1998.pdf][~/Papers/WattsStrogatz1998.pdf]]
  - [[~/Papers/Newman2003.pdf]]
  - [[~/Papers/Strogatz2001.pdf]]


  
